### ISSUE TITLE
Create proper UI for Deep RL trainer class 

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#102]
I thought the UI should look something like this (open to suggestions obviously):

```python
from genrl import PPO1
from genrl.deep import Trainer
import gym

env = gym.make('CartPole-v0')
agent = PPO1(...)
trainer = Trainer(env, agent, logger='stdout', ...) # instead of separate logger object
trainer.train()
```

**Comment by Sharad24** [comment]
So only changing the logger?

**Comment by ajaysub110** [comment]
Nope. Right now, the user is required to call either on policy trainer or
off policy trainer based on type of algo. Thought we could avoid this with
just a trainer call which automatically figures things out.
