### ISSUE TITLE
Unified Trainers

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#103]

**Comment by Sharad24** [comment]
Are you moving ahead on this? @ajaysub110

**Comment by ajaysub110** [comment]
Nope

**Comment by Sharad24** [comment]
We should have the ability to provide one single Trainer API which is able to train any agent + env, etc.

For e.g. HuggingFace has such an API.

**Comment by sampreet-arthi** [comment]
Tracking in #382
