### ISSUE TITLE
Clean up docs

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#104]
* Fix docstring warnings
* Remove pytorch links and other unnecessary stuff

**Comment by Sharad24** [comment]
Adding docstrings to methods is also important. We're missing them in almost every method. This should not take a lot of time I think and also help us in figuring out the assumptions we're making everywhere (which we should remove).

- [ ] DQN (@Het-Shah )
- [ ] PPO (@Sharad24 )
- [ ] DDPG (@ajaysub110 )
- [ ] TD3 (@Sharad24 )
- [ ] VPG (@Het-Shah )
- [ ] SAC (@ajaysub110 )
- [ ] VecEnvs
- [ ].Bandits
- [ ] Buffers
- [ ] Policies
- [ ] Values
- [ ] Base
- [ ] Actor Critic
- [ ] Trainers
- [ ] Utils
- [ ] Logger
- [ ] Noise
- [ ] ClassicalRL models
- [ ] ClassicalRL Trainers
- [ ] ClassicalRL Q-Learning
- [ ] ClassicalRL SARSA

**Comment by Sharad24** [comment]
Tracking is #144
