### ISSUE TITLE
Classical RL models for model-based RL

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#105]
As of now, only sample-based `TabularModel` is implemented which works only for deterministic, discrete environments. More models to implement:
- [ ] ExpectationModel
- [ ] GaussianModel
- [ ] Gaussian Mixture Model

**Comment by Sharad24** [comment]
I'll work on adding some of these

**Comment by Sharad24** [comment]
Lets close these issues and just handle these in projects? (Algorithms that we plan to add that is)

**Comment by ajaysub110** [comment]
Sure

**Comment by Het-Shah** [comment]
Is anyone working on these? If not I'll do it, I am currently not working on any issues anyway

**Comment by Sharad24** [comment]
Yup go ahead, I'm not working on anything. Could you also please figure out benchmarking params for DQN? I know this is much easier but still.

Once we have trained agents we can add it to our documentation/README to beautify the repo. That will easily fetch 100s of stars.

**Comment by Het-Shah** [comment]
>  Could you also please figure out benchmarking params for DQN? 

Will do this.. Let the DQN's CNN implementation be fixed first.
