### ISSUE TITLE
Vectorization

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#118]
Vectorization might take some time as otherwise anticipated. I'm facing the following issues really:

1. Rollout Buffers also have to be vectorized. Most buffers just push into a collections object. New buffers will have to maintain a vectorized state and at the same time these trajectories should be kept intact. Terminal observations should be checked because after that at the index in the vectorized collection new trajectories have started (This really is the main issue). 
2. Algorithms. Direct reshaping is not possible in most envs. As terminal conditions have to be taken care of. Also, env resetting conditions.
3. Logging standardization: Should we store timesteps/episodes/etc. Most of these would just be mean.
4. Standardization of callback timesteps. E.g. logging_interval, policy_update_interval, policy_copy_interval, etc. These values get greatly affected with an increasing number of envs running in parallel.

Most algos will face a major re-write. So it'll probably be until the end of the week until its complete.

**Comment by Zeus3101** [comment]
Suggestion: Can we have the VecEnv method `get_spaces` be 2 separate methods as `observation_space` and `action_space`? This would be seamless to integrate later on with wrappers and would be uniform too.

**Comment by Sharad24** [comment]
Yup, have it in my PR #111
