### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#12]
Add other basic policies such as 

- [x] CNNPolicy (Nature CNN)
- [ ] LSTMPolicy
- [ ] CNNLstmPolicy (Nature CNN)
- [ ] ImpalaCNNPolicy
- [ ] ImpalaCNNLstmPolicy

**Comment by Zeus3101** [comment]
For a CNN Policy, since we will be mostly applying it for Gym Atari environments, would it be fine to take the settings as in the original DQN paper?

**Comment by Sharad24** [comment]
Yes. The architectures mentioned above are standard in RL

**Comment by Sharad24** [comment]
@threewisemonkeys-as You were working on Impala right? Any chance we could fit some of it in here?

**Comment by threewisemonkeys-as** [comment]
I haven't added the CNN/LSTM policy to that yet, only built the actor / learner architecture so far with an Mlp policy.

**Comment by sampreet-arthi** [comment]
I don't think we need any LSTM policies right now? Impala CNN would be nice for Atari tho.

**Comment by hades-rp2010** [comment]
Can I take this up?
@sampreet-arthi said that there is support missing on the envs that require LSTM policies.. but still.. making it complete might help
Same for CNNLSTM.. Not sure if I can do the Impala ones tho

**Comment by Sharad24** [comment]
It might be a better idea to work on #194 first. After which new policies will be easy to add

**Comment by mehulrastogi** [comment]
Would just like to point out my comment in #222. Should we focus more on making policies easily extendible? Instead of adding multiple policies and passing string arguments for each policy?

**Comment by hades-rp2010** [comment]
I guess its already implemented in #205  with support for custom policies, values and actorcritics
