### ISSUE TITLE
Exploration methods for action selection

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#122]
- [ ] Epsilon greedy
- [ ] Boltzmann exploration
- [ ] Parameter noise
- [ ] Random Network Distillation
- [ ] Pseudo counts?

**Comment by Zeus3101** [comment]
Where do we add these methods? As a file in common like `exploration.py` or as part of the Trainer class?

**Comment by ajaysub110** [comment]
I think we should add this to a separate file exploration.py and add explore as a parameter to offpolicytrainer. @Sharad24 @Het-Shah ?

**Comment by Sharad24** [comment]
Separating files as much as possible is definitely better. `Trainer.py` is already above 250 lines(in `deeprl`) which means that we can structure it much better.

So I'm up for a separate file

**Comment by Het-Shah** [comment]
Yea, I agree with @Sharad24, the `Trainer.py` file is already a bit long

**Comment by ajaysub110** [comment]
@Zeus3101 @Het-Shah @Sharad24 are any of you working on this or can I take this up?

**Comment by Sharad24** [comment]
I'm still working in vectorization

**Comment by Zeus3101** [comment]
I could work on it but might take some time as I need to read up on them. If you want to do it go ahead though.

**Comment by Zeus3101** [comment]
I'm working on #125 atm. It would take me too long to implement this anyway as I would have to read up on everything :P

> @Zeus3101 @Het-Shah @Sharad24 are any of you working on this or can I take this up?

**Comment by ajaysub110** [comment]
Cool I'll take it up

**Comment by Sharad24** [comment]
Up for grabs
