### ISSUE TITLE
Refactor bandits.py into Policies and Bandits

### ISSUE THREAD

**Issue by threewisemonkeys-as** [SforAiDl/genrl#123]
Currently both bandits and policies are included in a single class. By separating these, there can be a standard api which would be useful for deep contextual bandits.

There are also a couple of issues with Bernoulli Bandits
1. The policy q values aren't currently independent with bandit reward probabilities
2.  `avg_reward` is being updated with a list of rewards from each step instead of the mean

**Comment by Sharad24** [comment]
Ok, these are two separate issues. I'll create an issue for the issues with Bernoulli Bandits. Are you going to work on these?

**Comment by Sharad24** [comment]
Also, @threewisemonkeys-as , could you also check what changes we need to make to policy functions we have in `deep`, so that they are compatible here?

**Comment by threewisemonkeys-as** [comment]
> Ok, these are two separate issues. I'll create an issue for the issues with Bernoulli Bandits. Are you going to work on these?

Yeah, I will work on this. I dont know how to claim the issue though.

**Comment by threewisemonkeys-as** [comment]
> Ok, these are two separate issues. I'll create an issue for the issues with Bernoulli Bandits. Are you going to work on these?

Yeah, I will work on this. I dont know how to claim the issue though.

**Comment by threewisemonkeys-as** [comment]
> Also, @threewisemonkeys-as , could you also check what changes we need to make to policy functions we have in `deep`, so that they are compatible here?

Compatible here in what sense?
The policy API would be the same since `select_action`, `update_params` and `learn` are all being implemented here.

**Comment by Sharad24** [comment]
That's great then :)

> > Also, @threewisemonkeys-as , could you also check what changes we need to make to policy functions we have in `deep`, so that they are compatible here?
> 
> Compatible here in what sense?
> The policy API would be the same since `select_action`, `update_params` and `learn` are all being implemented here.

Thats great then :)

**Comment by Sharad24** [comment]
Resolved in #127
