### ISSUE TITLE
Set up CD workflows

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#132]

**Comment by Zeus3101** [comment]
What do we want to do here? Deploy on AWS or Azure?

**Comment by Sharad24** [comment]
No. For nightly release.

**Comment by Sharad24** [comment]
More importantly, a CD workflow from a release branch so that whenever it gets a commit, a new package is deployed

**Comment by Zeus3101** [comment]
So we add this after releasing v0.1?

**Comment by Sharad24** [comment]
Closing this for now
