### ISSUE TITLE
Docs not building

### ISSUE THREAD

**Issue by Zeus3101** [SforAiDl/genrl#133]
A2C docs are not building for some reason, can't figure out why.

**Comment by Zeus3101** [comment]
Update: It doesn't work for the documentation in #128 either. It seems to be only generating documentation for the files that were there until some previous commit. (Because it gives a warning that VecEnvs.py was not found when the PR doesn't even have a file called VecEnvs.py)

**Comment by Sharad24** [comment]
Tracking in #144
