### ISSUE TITLE
Issues with Logger

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#134]
1. Stdout logger shows wrong timestep
2. Tensorboard logger saves one event file for each episode. Is this normal?

**Comment by Sharad24** [comment]
Also, beautify the printing format. Right now it just prints numbers directly. It would be good to control precision of numbers like episode rewards, etc which have a lot of decimals

**Comment by Het-Shah** [comment]
> Stdout logger shows wrong timestep

For which trainer?

> Also, beautify the printing format. Right now it just prints numbers directly. It would be good to control precision of numbers like episode rewards, etc which have a lot of decimals

We are logging only reward i guess as of now for train and for evaluate method we have mean and reward. I'll set all of those with precision 4.

**Comment by ajaysub110** [comment]
The timestep thing isn't fixed yet right?

**Comment by Het-Shah** [comment]
Is the timesteps issue only with DQN or do you face this issue with any other agent?

**Comment by Sharad24** [comment]
Its probably better to just use `episodes` than `timesteps`

`timesteps` is always confusing and depends on a lot of thing.

Any thoughts?

**Comment by ajaysub110** [comment]
Since episode sizes vary across games, it'll be hard to compare different
games on difficulty level, if we use number of episodes. I think this is
also why most papers use timesteps

**Comment by Sharad24** [comment]
Hmm yeah, could also get confusing when there an agent has >1 lives

**Comment by Het-Shah** [comment]
I don't really think there is an error with the timesteps. I printed the whole training process seems good to me.

**Comment by Sharad24** [comment]
I'm going to close this, reopen if still an issue
