### ISSUE TITLE
Save method of Trainer class needs some changes

### ISSUE THREAD

**Issue by Zeus3101** [SforAiDl/genrl#137]
Unlike the `save_params` function in `utils.py`, the Trainer class only uses `logs/checkpoints/algo_name-env_name/experiment` to save the hyperparams. 
Also, it currently uses `self.env.envs[0].unwrapped.spec.id` making it work only for VecEnvs. Not sure if Travis checks for the Trainer save function.

Propose to replace the save function with the save_params utility function. As for the second part, it can be taken care of using Wrappers by assigning a property like say, `env_id`

**Comment by Sharad24** [comment]
We could just add an `env_id` property to the VecEnv class, maybe?

**Comment by Zeus3101** [comment]
Yeah, but we still need to format the code though. The `save_params` method saves with `run_num` and `timestep` which is more useful.
