### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#144]
Combining all issues with docs into one.

1. Remove generated .rst files in docs for e.g. (`genrl.rst`) #142 
2. Docs currently are not building #133 
3. Clean up docs #104 
4. Search in docs does not work #130

**Comment by Zeus3101** [comment]
Is someone still working on this?

**Comment by ajaysub110** [comment]
This can be closed right?

**Comment by Sharad24** [comment]
Yes, I think so.

**Comment by Sharad24** [comment]
On a related topic, should we shift documentation build/testing on GitHub Actions? It seems much faster, plus we can distribute one to Actions and one to Travis

**Comment by ajaysub110** [comment]
Yeah agree, preferably shift docs to actions rather than tests since docs
are independent

**Comment by Sharad24** [comment]
I was thinking of tests, because there's this stage of symbol exporting happening for some Python wrapper libraries on Travis. This alone takes like 7/8 minutes of the build which is very annoying.

**Comment by ajaysub110** [comment]
Right, that's a bigger issue. Cool then
