### ISSUE TITLE
Creating Contextual Bandits with Categorical Context 

### ISSUE THREAD

**Issue by threewisemonkeys-as** [SforAiDl/genrl#145]
1. Create new `ContextualBandit` class which will define multiple bandits internally
2. Which Bandit is being served will be the context being given to the policy
3. `step` function will return both reward and context
4. Creating a `gym` environment style wrapper for the bandit

We would also need to implement various algorithms to solve the bandit

**Comment by Sharad24** [comment]
Sounds good! What dataset are you going to be testing on?

**Comment by threewisemonkeys-as** [comment]
Wouldn't we initially  just be testing on M different k-armed gaussian bandits at first? I.e. each bandit would have Gaussian reward distribution with a random mean for each arm.

Also, I dont have much idea about datasets for CBs. I found [one](http://www.cs.columbia.edu/~jebara/6998/dataset.txt) for news article and [another ](https://webscope.sandbox.yahoo.com/catalog.php?datatype=a) for ad recommendations.

**Comment by Sharad24** [comment]
> Also, I dont have much idea about datasets for CBs. I found [one](http://www.cs.columbia.edu/~jebara/6998/hw2.pdf) for news article and [another ](https://webscope.sandbox.yahoo.com/catalog.php?datatype=a) for ad recommendations. Are there any established ones we can use?

Yeah I think the standard usually is a [bibtex dataset](http://manikvarma.org/downloads/XC/XMLRepository.html). But you can try the ones you mentioned also. 

Also, I think we'd be doing M different k-armed Bernoulli Bandits. Based on the context which has binary variables, we'd be selecting the bandit. Gaussian should probably be a step after this.

**Comment by threewisemonkeys-as** [comment]
Just to be clear, right now we will create a testbed of sorts where the rewards distributions are autogenerated as opposed to a dataset. So the m k-armed bernoulli bandits can be modelled with an (m, k) - dim matrix of probabilities for getting the reward. In each iteration the policy will be given the number of the bandit as context and the policy will choose an arm accordingly.

The bibtext dataet has around 2000 possible features (binary) so the state space would be massive. So we would work on this after creating the initial testbed.

In this PR I am working on bandit class for the testbed. This is my understanding till now, am I missing anything? I was just a little confused about the exact problem definition.

**Comment by ajaysub110** [comment]
Good point! As you said, it would be wiser to build a simple testbed with randomly generated rewards first, following which we can move to the bibtex (or any other) dataset. 
And yes, let's store the value estimates as a table as of now with `n_bandits` rows and `n_arms` cols. We can later replace this with a deep value network.
A suggestion, implement a generic class within classical/commons/values.py. We can use these classes in the existing Qlearning and SARSA implementations as well.

**Comment by threewisemonkeys-as** [comment]
> A suggestion, implement a generic class within classical/commons/values.py. We can use these classes in the existing Qlearning and SARSA implementations as well.

Isnt this what `models.py` is doing? 
Also we will need to add method to update the value function which is kind of redundant for a simple table

**Comment by ajaysub110** [comment]
Nope, `models.py` is for the transition models that predict next states and rewards. Models are only applicable for model-based algorithms. Here, we're talking about tables for the value function.

**Comment by Sharad24** [comment]
Anything left here? @threewisemonkeys-as 

If we're done here, I think we have to move to the two other things, which is NN integration and dataset.

**Comment by threewisemonkeys-as** [comment]
Yeah this is done. I have been looking into some deep CB implementations. Will open an issue tomorrow.
