### ISSUE TITLE
Potential model architecture issues

### ISSUE THREAD

**Issue by infinitemugen** [SforAiDl/genrl#146]
Came across this issue while running my Hindsight Experience Replay code with the Dueling DQN architecture. The environment used was the Bit Flipping Environment proposed in [this paper](https://arxiv.org/abs/1707.01495).

The Dueling DQN model built by the repository fails to succeed on the environment, but the model proposed in the paper succeeds perfectly, even though the differences do not seem too significant to me.
For reference, the model built by the repository:
```
DuelingDQNValueMlp(
  (feature): Sequential(
    (0): Linear(in_features=100, out_features=128, bias=True)
    (1): ReLU()
  )
  (advantage): Sequential(
    (0): Linear(in_features=128, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=50, bias=True)
  )
  (value): Sequential(
    (0): Linear(in_features=128, out_features=128, bias=True)
    (1): ReLU()
    (2): Linear(in_features=128, out_features=1, bias=True)
  )
)
```
The other model I used, with which I found success:
```
DuelingMLP(
  (linear): Linear(in_features=100, out_features=256, bias=True)
  (value_head): Linear(in_features=256, out_features=1, bias=True)
  (advantage_head): Linear(in_features=256, out_features=50, bias=True)
)
```
The code and hyperparameters used were exactly the same in both cases, so I believe that the model architecture is what's making the difference here.

Success rate graphs for both of them respectively:
![image](https://user-images.githubusercontent.com/48847874/83325497-41b83800-a28a-11ea-90db-29a7396e29eb.png)

![image](https://user-images.githubusercontent.com/48847874/83325506-4da3fa00-a28a-11ea-90db-6dafeb93ebcd.png)

I had the exact same issues with vanilla DQNs as well.

The code that I used can be found[ here](https://colab.research.google.com/drive/1Y8vEHOETH6uDN5GxXJoFeqiu6vvkacP5?usp=sharing).

**Comment by Sharad24** [comment]
So just an architecture difference, is it? Nice, I think we need to log results + hyperparams + checkpoints

cc: @ajaysub110 @Het-Shah  @Zeus3101

**Comment by Het-Shah** [comment]
I didn't understand how our model is not faring well, I mean what can be the errors in that.

**Comment by Sharad24** [comment]
Yeah kinda agree, I dont expect it to get *0*

**Comment by infinitemugen** [comment]
It is surprising to me too, but the only thing I've changed in the code is the model. You can check out the notebook and run it yourself if you want to confirm things.

**Comment by Het-Shah** [comment]
Yea, it can be worse but a flat line is very wierd :(

**Comment by ajaysub110** [comment]
Can it be something to do with concatenating multiple `Sequential`s like that?

**Comment by Sharad24** [comment]
Need to do a bit more digging on this. Seems like some silly error. If someone takes a look at this, check if the model weights are updating.
