### ISSUE TITLE
Args, kwargs in Agents

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#152]
Use dict in classes to assign params to self.__dict__ dict directly rather than assigning each and every variable. This would help in making agent files smaller.

A for loop over the arguments dict should work

**Comment by mehulrastogi** [comment]
Instead of a dictionary (looping key word arguments dict) shouldn't we use Args directly?
Something like in the following post :- 
[https://stackoverflow.com/a/28399254](https://stackoverflow.com/a/28399254)

**Comment by Sharad24** [comment]
Can you give an example?

**Comment by mehulrastogi** [comment]
Right now most of the agents use the following strategy:- 
```python

class PPO1(OnPolicyAgent):
    

    def __init__(
        self,
        network: Union[str, BaseActorCritic],
        env: Union[gym.Env, VecEnv],
        batch_size: int = 256,
        gamma: float = 0.99,
        clip_param: float = 0.2,
        epochs: int = 1000,
        lr_policy: float = 0.001,
        lr_value: float = 0.001,
        layers: Tuple = (64, 64),
        rollout_size: int = 2048,
        **kwargs
    ):

        super(PPO1, self).__init__(
            network,
            env,
            batch_size=batch_size,
            layers=layers,
            gamma=gamma,
            lr_policy=lr_policy,
            lr_value=lr_value,
            epochs=epochs,
            rollout_size=rollout_size,
            **kwargs
        )

```

This has some major problems. First does not let me access the parent class arguments (BasePolicy.create_model). Second, if any argument added to base class it will become very tedious to change all the agents. The third code becomes long :) . 

Instead, we can do something given in [https://stackoverflow.com/a/28399254](https://stackoverflow.com/a/28399254):-

```python
class Base(object):
    def __init__(self, base_arg0, base_arg1, base_arg2):
        pass

class Derived(Base):
    def __init__(self, derived_arg, *args):
        super().__init__(*args)
```

and define object of derived class as Derived(da, ba0, ba1, ba2)

**Comment by sampreet-arthi** [comment]
Ig this issue can be closed now. We haven't added a dict but just used *args and **kwargs for inherited arguments. Documentation still covers all the arguments being passed so it's not unclear.
