### ISSUE TITLE
VecEnv render does not work

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#153]
Found in #111

**Comment by Sharad24** [comment]
Some resources @ajaysub110 found:
- https://www.reddit.com/r/reinforcementlearning/comments/a3mwfn/openai_gym_how_to_get_pixels_in_classic_control/
- https://github.com/Rowing0914/TF_RL

**Comment by sampreet-arthi** [comment]
This might help here: https://github.com/openai/gym/pull/1624

**Comment by sampreet-arthi** [comment]
Tracking in #382
