### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#156]
Ideally, every function should have a `get_logging_params` method which returns logging values. Couple of ways to do this: 

- Either return these values in a function call to the trainer which can then call the logger appropriately
- Store these values inside the agent such that when `get_logging_params` is called, these values are returned.

1st option should be a better solution to this.

**Comment by Zeus3101** [comment]
Does logging to csv work properly? My train.csv file is empty every time. Maybe take a look at this too.

**Comment by Zeus3101** [comment]
Couple more issues:
- Train.csv is always empty. The CSV Logger may not be working.
- Logging doesn't seem to work on Colab.

**Comment by Sharad24** [comment]
I think you're checking the wrong file. Have you checked `logs/train.csv`?

**Comment by Zeus3101** [comment]
I'm not getting a `logs/train.csv`. I'm getting a `train.csv` in the root folder and a `logs/train.log`

**Comment by Sharad24** [comment]
Are you specifying the log directory when you instantiate the trainer?

Its working for me, not sure why its not working for you

**Comment by Zeus3101** [comment]
It's working now
