### ISSUE TITLE
Standardize function calls in OffPolicyAgents

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#157]
The OnPolicy agents were modified to work with just 3 calls and hence all of them seamlessly integrate with the OnPolicyTrainer.

It would be good to do this for the off-policy agents as well. Possibly have a function called `observe`? Followed by buffer sampling and updating in another function, etc. 

Feel free to ignore the above though, if you have a better idea in mind.

**Comment by Sharad24** [comment]
Need to reduce _Cognitive Complexity_.

**Comment by Het-Shah** [comment]
Closing this already merged.
