### ISSUE TITLE
Issues with PPO1, VPG, A2C

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#160]
Might be resolved in #128

**Comment by Zeus3101** [comment]
Is the issue that the algos are not learning? Or is it that they aren't working at all? SAC, TD3 and DDPG seem to be working fine for LunarLanderContinuous-v2 and BipedalWalker.

With CarRacing and a couple of other envs like CubeCrash, the state space is Box(a, b, c) so it would have to use a CNN network. I'll sort this out in #128.

**Comment by Sharad24** [comment]
Hmm, let me change it a bit. SAC, TD3 and DDPG are supposed to be taking deterministic policy gradients so I meant PPO, A2C and VPG.

**Comment by Zeus3101** [comment]
It's not just Box2D, they don't seem to be training for any environment so far that I've tried. (On master and with wrappers).

**Comment by Zeus3101** [comment]
Also, render doesn't work for `OnPolicyTrainer`

**Comment by Zeus3101** [comment]
A summation of all issues so far:
- [ ] None of them (PPO, A2C, VPG) do not train on continuous environment
- [ ] VPG doesn't work at all with Pendulum-v0
- [ ] A2C is not learning at all, reward is practically constant
- [ ] PPO1 and VPG are not completing CartPole-v0 (Howering around 170-190 but not reaching 200)
- [ ] Rendering is not available for an OnPolicy algo (as OnPolicyTrainer doesn't have the functionality)

**Comment by Sharad24** [comment]
I just tested locally by printing the rewards. They do reach 200. So its some bug somewhere.

**Comment by Sharad24** [comment]
Resolving in #170
