### ISSUE TITLE
Save/Load extra features.

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#161]
Add functionality to save:
- Current Timestep:  When we start training DQN, we need to keep it running till the end for proper results (because every time you load a pre-trained model, the epsilon value will reset to 0.01 which is not very productive).
- Loss, reward and average Q-value history (for DQN) or average return (for SAC, TD3 etc) : Can be used to make plots and would help for benchmarking later on.

These can either be done in #128 or as part of the `save_params`, `get_hyperparams` methods. Any thoughts @Sharad24 @ajaysub110 @Het-Shah ?

**Comment by Sharad24** [comment]
Why only DQN though?

**Comment by Sharad24** [comment]
Feel free to add these in your PR. And while you're at it, can you think of a way to implement the evaluation callback? It shouldn't be that hard tbh, as an evaluation already exists.

**Comment by Sharad24** [comment]
Wait, sorry. Dont add these changes of yet. I think there might be some things that become redundant. Lets wait for what the others think.

**Comment by Zeus3101** [comment]
>Why only DQN though?
>
>edit: Asking about the second point.

I meant Q-values as an example because I was working with DQN at the time. We can also keep a track of average return or average value etc depending on the algo.

**Comment by Zeus3101** [comment]
>Feel free to add these in your PR. And while you're at it, can you think of a way to implement the evaluation callback? It shouldn't be that hard tbh, as an evaluation already exists.

What do you mean by evaluation callback?

**Comment by sampreet-arthi** [comment]
This is issue seems mostly redundant. Part of it is #181 and losses, rewards are being saved by the logger. We could add Q-values and Average returns to the logs instead in #187 . Is that fine?

**Comment by Sharad24** [comment]
Has this been resolved?

**Comment by sampreet-arthi** [comment]
No I don't think so

**Comment by sampreet-arthi** [comment]
This could be done later. Right now, the off policy algos need to be refactored. We could open this to new contributors once that's done.
