### ISSUE TITLE
Use PushReplayBuffer in Off Policy Algos

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#165]
Nothing wrong with the current ReplayBuffer but PushReplayBuffer is the ideal one to use﻿

**Comment by Zeus3101** [comment]
Maybe we should select based on which is faster?

**Comment by Sharad24** [comment]
No, its just that PushReplayBuffer is a more standard way to do it.

**Comment by sampreet-arthi** [comment]
We can do this with #169
