### ISSUE TITLE
Base classes for Off Policy Agents

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#169]
This should make the code much more comprehensible, especially with the number of arguments we have. And at the same time resolve a lot of maintainability issues.

**Comment by Zeus3101** [comment]
There's also a lot of code duplication issues that show up pylint. Maybe work on that too.

**Comment by Sharad24** [comment]
Yup, that's the goal. Another thing to do would be properly decide the parameters to be kept/removed in agents and added/removed from the trainers.

**Comment by sampreet-arthi** [comment]
Since we already have the On Policy Agents, I'm renaming this to Off Policy. I'll raise a PR for this soon.

**Comment by sampreet-arthi** [comment]
I'm thinking of refactoring each of the individual off policy algorithms first so that the code is neater, more uniform and shorter.

**Comment by sampreet-arthi** [comment]
To-do:
- [ ] Refactor DDPG
- [ ] Refactor TD3
- [ ] Refactor SAC
- [ ] Finalise BaseAgent and Base OffPolicyAgent classes
- [ ] Refactor Trainer and OffPolicyTrainer (Trainer classes are also really long, would be a good idea to first shorten them then maybe we can separate them into multiple files if they're still too big)

**Comment by Sharad24** [comment]
Tracking in separate issues now. #263, #162 and #264
