### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#174]
- Remove relative importing
- Remove 'vec_' prefix in vec_envs﻿

**Comment by Zeus3101** [comment]
Should we remove relative imports altogether? I figured we decided to let them be, right?

**Comment by ajaysub110** [comment]
I think should be removed too. I had originally added them cause I thought that would remove all the non user-facing modules from the docs. But it didn't work. So we need to figure something out for that as well.

**Comment by sampreet-arthi** [comment]
Should we work on this? The vec_ prefix has already been removed.

**Comment by sampreet-arthi** [comment]
@Sharad24

**Comment by Sharad24** [comment]
Yeah, we should remove all relative imports

**Comment by duttaANI** [comment]
I would like to work on this issue

**Comment by sampreet-arthi** [comment]
The files we have now can be categorised into:

- [ ] Agents
- [ ] Common
- [ ] Environments
- [ ] Classical Bandits
- [ ] Other Classical

Let me know which one of these you'll work on. (You can take more if you want)

**Comment by duttaANI** [comment]
I will start with Agents

**Comment by duttaANI** [comment]
I will take up common

**Comment by duttaANI** [comment]
@sampreet-arthi  Could you provide the path for Other Classical folder. The Common and Environments files have been completed.

**Comment by sampreet-arthi** [comment]
Other classical in the sense files other than in `classical/bandits`

**Comment by sampreet-arthi** [comment]
Resolved in #206
