### ISSUE TITLE
Actor Critic class to support multiple critics

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#190]
Some agents like SAC and TD3 will require multiple critics (q1, q2), we could add support for those by adding another actor critic class that uses `self.ac.qf1`, `self.ac.qf2` or maybe a tuple which can be used like `self.qf1, self.qf2 = self.ac.critic`

**Comment by Sharad24** [comment]
Ideally the `ActorCritic` class should be agnostic of such definitions rather than us defining another class for this. 

Another design could be to keep the `ActorCritic` definition as a base class and have `SingleActorSingleCritic`, `SingleActorMultipleCritic`, etc

**Comment by sampreet-arthi** [comment]
I was thinking of the second approach

**Comment by sampreet-arthi** [comment]
TD3 and SAC will require these and I'm refactoring them rn so I'm taking this up

**Comment by Sharad24** [comment]
Make sure to open a separate PR for this and not have the off policy refactoring in the same PR.
