### ISSUE TITLE
Easy usage for adding custom policies

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#194]
As discussed in the last meet, we could introduce functionality for adding custom policies by modifying the usage of `network_type` by allowing the user to pass an explicitly defined Policy if they want to. This would obviously extend to Value and Actor Critic functions too. Do we want to introduce something like this? 

Example from Stable Baselines: https://stable-baselines.readthedocs.io/en/master/guide/custom_policy.html

**Comment by Sharad24** [comment]
Yes, this is very much required. #146 is a related issue
