### ISSUE TITLE
Remove imports from deep/common

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#203]
Here's a suggestion. Right now, some code maybe written as:
`from genrl.deep.common import OffPolicyTrainer, Logger, ReplayBuffer, get_env_properties, get_model`

We should remove the imports from the `__init__.py` under `deep/common` so that they're only accessible as:
```
from genrl.deep.common.trainer import OffPolicyTrainer
from genrl.deep.common.logger import Logger
from genrl.deep.common.buffers import ReplayBuffer
from genrl.deep.common.utils import get_env_properties, get_model
```

This will make the code easier to read, understand and more logical than cluttering them all under a single package under common.

**Comment by Sharad24** [comment]
This should be done for the whole codebase. Especially for the agents, otherwise all of them look like packages.

**Comment by IshanDaga** [comment]
I can take this up if no one else has yet

**Comment by IshanDaga** [comment]
Just a sanity check, the current `__init__.py` file under `deep/common` looks like this  : 

`from genrl.deep.common.actor_critic import MlpActorCritic 
from genrl.deep.common.actor_critic import get_actor_critic_from_name`

And from what I've understood the new file should look like this :

`from genrl.deep.common import actor_critic`

**Comment by sampreet-arthi** [comment]
No. The `__ init__.py` files are to tell python where to look for the different classes and functions. Think of it as a sort of tree telling where different things are located. 

What you would need to do is to go to the other files like for example maybe `a2c.py` and do the opposite of what you said. Refer to the initial message to see what needs to be done.

Raise a PR with some initial changes. If you have any doubts we can address them there.
