### ISSUE TITLE
Custom Buffers

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#218]
The current buffers we have are not ideal implementations and it's hard to use the same buffers for different kinds of envs. It would be helpful to also have a customizable buffer which can be sent as an input. Refer to the `OffPolicyAgent` class variable `buffer_type` and #205. Similar change needs to be done for OnPolicy Rollouts too. Currently, creating an agent with a custom buffer would require the agent to import a bunch of other stuff from GenRL like `get_env_properties` and `get_model` which should probably not be user-facing.

**Comment by Sharad24** [comment]
I think you can use Reverb for everything. And there is an issue for that #151

**Comment by sampreet-arthi** [comment]
Ok sorry, didn't see the name change. This can be tracked in #151 then. Closing this.
