### ISSUE TITLE
Actor Critic hidden layers

### ISSUE THREAD

**Issue by sampreet-arthi** [SforAiDl/genrl#222]
Currently, both the actor and the critic have the same number of hidden layers being used. It might be different depending on the paper so this should be added may be as `value_layers` and `policy_layers` or critic/actor layers instead.

**Comment by hades-rp2010** [comment]
So i guess changing the args of both the MlpActorCritic and the CNNActorCritic class in actor_critic.py will do?

**Comment by sampreet-arthi** [comment]
Yeah, but you'll also have to add an additional argument to all the agent classes. Either that or the `layers` arg can be a list of lists. First item corresponding to the actor and the second for the critic.

It's not a priority as of now imo. They're usually about the same afaik. This will just add more customizability as there might be use cases where more layers are needed for the critic (or the actor)

**Comment by mehulrastogi** [comment]
Why do we want to even restrict ourselves to only dense layers? In my opinion, both the policy and value should have the capability to be flexible extensively. Something like the following:- 

`
class CustomPolicy(BasePolicy):
    pass

class CustomValue(BasePolicy):
    pass


class CustomActorCritic(BaseActorCritic):
    def __init__(CustomPolicyobj , CustomValueobj):
        super(CustomActorCritic, self).__init__()

        self.actor = CustomPolicyobj
        self.critic = CustomValueobj
`

Here there is the option for anyone to have their own policies and value functions. Advantage can be that we can have some default policy/value functions (right now fixed mlp/CNN) but the API provides a way to make t easily extendable. IMO we should extend this to not only Actor-Critic but also to policy and values in general. I anyways will have to do this for evolutionary algorithms!!

**Comment by sampreet-arthi** [comment]
> Why do we want to even restrict ourselves to only dense layers? In my opinion, both the policy and value should have the capability to be flexible extensively. Something like the following:-
> 
> ```python
> class CustomPolicy(BasePolicy):
>     pass
> 
> class CustomValue(BasePolicy):
>     pass
> 
> class CustomActorCritic(BaseActorCritic):
>      def __init__(CustomPolicyobj , CustomValueobj):
>         super(CustomActorCritic, self).__init__()
> 
>         self.actor = CustomPolicyobj
>         self.critic = CustomValueobj
> ```
> 
> Here there is the option for anyone to have their own policies and value functions. Advantage can be that we can have some default policy/value functions (right now fixed mlp/CNN) but the API provides a way to make t easily extendable. IMO we should extend this to not only Actor-Critic but also to policy and values in general. I anyways will have to do this for evolutionary algorithms!!

@mehulrastogi could you raise a specific PR for tackling this? Maybe you or @hades-rp2010 could work on this.
