### ISSUE TITLE
Shared Parameters between actor and critic

### ISSUE THREAD

**Issue by hades-rp2010** [SforAiDl/genrl#225]
The actor and critics use a different network with no shared parameters currently. It can be modified to have a common base of shared layers and then branch out into 2 different heads - one being the actor and the other the critic. May be added as `shared_layers`, `policy_layers` and `value_layers`

**Comment by mehulrastogi** [comment]
But isn't the whole point of genrl is to let the user decide if he wants a shared parameter or not? I guess a better idea would be to have an option if the user wants shared params or not.

**Comment by hades-rp2010** [comment]
So a param that defaults to None, unless the user passes it explicitly sounds good?

**Comment by Sharad24** [comment]
Any issue with simply extending the `BaseActorCritic` directly?

**Comment by hades-rp2010** [comment]
> Any issue with simply extending the `BaseActorCritic` directly?

I think this should work, I'll try and if it does, I'll open a PR for the same

**Comment by hades-rp2010** [comment]
I'm running into shape errors in the agents that use Q(s,a).
I'll open a pr shortly

**Comment by sampreet-arthi** [comment]
@hades-rp2010 are you still working on this?

**Comment by hades-rp2010** [comment]
> @hades-rp2010 are you still working on this?
Yep

**Comment by sampreet-arthi** [comment]
Ok, raise a PR whenever you're ready. Take a look at the multiagent PR. I think it was implemented there.

**Comment by sampreet-arthi** [comment]
Can we close this? @hades-rp2010

**Comment by hades-rp2010** [comment]
> Can we close this? @hades-rp2010

Yeah, I'll close this
