### ISSUE TITLE
get_env_properties function

### ISSUE THREAD

**Issue by mehulrastogi** [SforAiDl/genrl#232]
Getting the env properties should not be dependent on the architecture as that can be custom. Changing the argument names as return value doesn't change.

https://github.com/SforAiDl/genrl/blob/ebf31b161133f0ffce95d14e3ef830a993dad203/genrl/deep/common/utils.py#L130

Tiny Issue

**Comment by sampreet-arthi** [comment]
The `input_dim` is inherently different for both the CNN and MLP architectures. How do you propose solving this?

**Comment by Sharad24** [comment]
@mehulrastogi You can work on this if you'd like to
