### ISSUE TITLE
Optuna

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#250]
Integration of Optuna for hyperparameter optimization and search.

**Comment by sampreet-arthi** [comment]
I'm testing it out with DQN and TD3 with a slightly modified evaluate method. It's working okay so far. How do you want to go about integrating it?

**Comment by Sharad24** [comment]
Does it work? If yes, let's get it in.

**Comment by sampreet-arthi** [comment]
Can add some more examples here for other agents. Feel free to take this up. Example code can be found in `examples`.

**Comment by sampreet-arthi** [comment]
Tracking in #382
