### ISSUE TITLE
Off-Policy Agents Tutorials

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#267]
Follow current On Policy Agent's tutorials.

**Comment by veds12** [comment]
Can I take this up?

**Comment by Sharad24** [comment]
Sure!

**Comment by veds12** [comment]
Apart from ddpg and dqn are there any other tutorials that need to be added? Couldn't locate other off-policy agents in the library

**Comment by Sharad24** [comment]
Yes, there's 5 DQN types, DDPG, TD3 and SAC.

**Comment by Sharad24** [comment]
Hey @veds12 

Any updates here?

**Comment by veds12** [comment]
I am done with DQN, Dueling DQN and almost done with noisy DQN. I'll finish rest of the DQNs, DDPG, SAC and TD3 by the end of this week

**Comment by sampreet-arthi** [comment]
Can you push all the changes so we can review along the way

**Comment by veds12** [comment]
Yeah. I'll put up a PR by evening

**Comment by veds12** [comment]
@sampreet-arthi tutorials for all the off-policy algorithms have been added. You can close this
