### ISSUE TITLE
Missing credits

### ISSUE THREAD

**Issue by araffin** [SforAiDl/genrl#271]
Hello,

nice work overall.

Let me get straight to the point:
it is no secret that the "deep" part of this library is heavily inspired by [Stable-Baselines](https://github.com/DLR-RM/stable-baselines3) (when not copied, for instance for the rollout storage). Although we appreciate such project, we find it unfortunate that no explicit mention of it is made in the README.

As a reminder, SB and SB3 are licensed under the open source MIT license. This license is permissive but still requires attribution.
That's why we would appreciate the explicit mention and a link in the readme ;)

Tagging SB maintainers here, so they are notified: @hill-a  @Miffyli @AdamGleave @erniejunior

**Comment by Sharad24** [comment]
Hi @araffin 

Let me fix this.
