### ISSUE TITLE
Comparison to other PyTorch RL libraries

### ISSUE THREAD

**Issue by janacht** [SforAiDl/genrl#274]
There is a large variety of reinforcement libraries using PyTorch, just to name a few

- https://github.com/ray-project/ray
- https://github.com/DLR-RM/stable-baselines3
- https://github.com/ikostrikov/pytorch-a2c-ppo-acktr-gail
- https://github.com/astooke/rlpyt
- https://github.com/thu-ml/tianshou
- https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch

For potential future users, it could be a big benefit to highlight the advantages / 
differences in design choices / performance differences to the above libraries in the README,
similar to https://github.com/thu-ml/tianshou#fast-speed.

**Comment by Sharad24** [comment]
Hi @janacht 

Thanks for pointing this out. Yes, we do need to add more details to the Readme.

**Comment by sampreet-arthi** [comment]
Tracking in #382
