### ISSUE TITLE
Support for PyTorch V1.5

### ISSUE THREAD

**Issue by bscoventry** [SforAiDl/genrl#276]
Hi,

I was wondering if there will be support for PyTorch 1.5. Currently the requirement seems to be V1.4, however there is no distribution of V1.4 which has my cuda version (10.1). 

Thank you

**Comment by Sharad24** [comment]
Hi @bscoventry 

We'll release a version for Pytorch 1.5 soon!

**Comment by sampreet-arthi** [comment]
Tracking in #382
