### ISSUE TITLE
Multi Discrete Envs Spaces

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#295]
At multiple places we assume there's only a single dimension in the observation/action space if the env is discrete.

E.g.

https://github.com/SforAiDl/genrl/blob/dc2d58bdade1c5239ccc0925aeda78d1dc59e972/genrl/environments/vec_env/vector_envs.py#L123

https://github.com/SforAiDl/genrl/blob/dc2d58bdade1c5239ccc0925aeda78d1dc59e972/genrl/environments/vec_env/vector_envs.py#L133

**Comment by sampreet-arthi** [comment]
This caused a bug in running continuous envs with On Policy algos when you tried to fix it ig. For example, PPO wasn't running on Pendulum-v0. I've reverted it back to what it was for now. Let's deal with this when we're working with multi discrete envs?

**Comment by sampreet-arthi** [comment]
Tracking in #382
