### ISSUE TITLE
GymWrapper is not compatible for multiagent-particle-env

### ISSUE THREAD

**Issue by AdityaKapoor74** [SforAiDl/genrl#324]
I believe we will have to write a separate wrapper or incorporate it into the current one. I think the former approach is better as we can add other new features to it as well

**Comment by veds12** [comment]
Using [Petting Zoo](https://www.pettingzoo.ml/) instead of multiagent-particle-env might be a better idea. The API is very similar to that of Gym

**Comment by Sharad24** [comment]
> Using [Petting Zoo](https://www.pettingzoo.ml/) instead of multiagent-particle-env might be a better idea. The API is very similar to that of Gym

+1

**Comment by sampreet-arthi** [comment]
Can we close this and #325 as we're shifting to Petting Zoo? @AdityaKapoor74 @veds12

**Comment by Sharad24** [comment]
Yes. Petting Zoo has suppose for particle envs too.
