### ISSUE TITLE
Add support for depricated gym 0.10.5 to support multiagent-particle-env

### ISSUE THREAD

**Issue by AdityaKapoor74** [SforAiDl/genrl#325]
Will need to have support for gym version 0.10.5 as it is a need for multiagent-particle-env repo to work fine. Some issues are to fix imports in various files. For example gym.spaces.Space is gym.Space in 0.10.5

**Comment by Sharad24** [comment]
Can you check if the multi agent algorithms work on something that has support for recent versions of gym? E.g. https://github.com/koulanurag/ma-gym

If they do work, I dont see a reason for adding support for deprecated softwares.
