### ISSUE TITLE
Importing A2C fails

### ISSUE THREAD

**Issue by bscoventry** [SforAiDl/genrl#349]
Hi,

When trying out different algorithms, I run into an import error for A2C. Code is from Advantage actor critic sample in the wiki:

```
import gym

from genrl import A2C
from genrl.deep.common import OnPolicyTrainer
from genrl.environments import VectorEnv

env = VectorEnv("CartPole-v0")
agent = A2C('mlp', env)
trainer = OnPolicyTrainer(agent, env, log_mode=['stdout'])
trainer.train()
```
and fails with ImportError: cannot import name 'A2C'

Setup is Python 3.6.8, Cuda 10.1

**Comment by hades-rp2010** [comment]
Could you try `from genrl.agents import A2C` instead?
