### ISSUE TITLE
Parameter loading/saving with TOML

### ISSUE THREAD

**Issue by Sharad24** [SforAiDl/genrl#352]
Docs do not render code.
https://genrl.readthedocs.io/en/latest/usage/tutorials/Saving%20and%20loading.html

**Comment by babu1998** [comment]
Need some more details
1. What is the code you are trying to render.
2. How do you update the text in the docs link given above.

**Comment by Sharad24** [comment]
The code can be found in this [PR](https://github.com/SforAiDl/genrl/pull/286/files) If you look carefully, the code does not get rendered due to formatting errors.
