### ISSUE TITLE
DQN

### ISSUE THREAD

**Issue by Het-Shah** [SforAiDl/genrl#36]
Add/remove the variants we should implement
- [x] DQN
- [x] Double Q Learning 
- [x] Dueling DQN
- [x] Prioritized Replay
- [x] Noisy Nets (Noisy DQN)
- [x] Distributional DQN
- [ ] Adapt multi step bootstrapped return from A3C

Refer #6

**Comment by Sharad24** [comment]
I think it would be nice to move towards implementing a [Rainbow DQN](https://arxiv.org/abs/1710.02298) type of formulation. Since that is the best DQN

**Comment by Het-Shah** [comment]
Should we leave this to the person using this? Like having options for individual implementations and then also having Rainbow DQN.

**Comment by Sharad24** [comment]
We can have one single implementation with these options being selected based on arguments in the constructor. E.g.

```DQN(env, noisy=False, target_networks=False, etc)```

What do you think?

**Comment by Het-Shah** [comment]
Yea that is what I was saying.. Having all the implementations and rainbow as well in one place.

**Comment by Het-Shah** [comment]
Just add to the checklist all the variants according to you...

**Comment by Sharad24** [comment]
Sounds good! Just updated. 

Some other info regarding this, it seems to me that having the Noisy Layers as separate neural network modules might be better than directly defining inside DQN. This way we can just call the Noisy Layer like any other pytorch nn module.

**Comment by Het-Shah** [comment]
Yup will add that in utils.py mostly.

**Comment by ajaysub110** [comment]
@Het-Shah when you're working on DQN, make sure that it is similar in structure to DDPG since their methods will be used in general by HER and TD3

**Comment by Het-Shah** [comment]
Ok, Sure.
