### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#86]
Add tests for all currently implemented algorithms to improve code coverage and ensure that newer commits do not cause unintended consequences.

**Comment by Sharad24** [comment]
If possible add tests for Base classes and functions first? As core algo functionalities will be changed with Trainer?

**Comment by ajaysub110** [comment]
Yeah makes sense

**Comment by Sharad24** [comment]
Lets make a checklist here?

**Comment by Sharad24** [comment]
There's tests left for these:

- Classical Algos like Q-Learning, SARSA, etc (@ajaysub110 )
- DQN (@Het-Shah )

**Comment by Sharad24** [comment]
I'm not adding VecEnvs since its not working correctly yet. Raising an issue for this

**Comment by Sharad24** [comment]
Only classical is left now. @ajaysub110 Feel free to add them when you have time.

**Comment by Zeus3101** [comment]
What about other stuff in common like buffers and noise?

**Comment by Sharad24** [comment]
These are tested when training the agents. You're more than welcome to add Unit tests for them though.
