### ISSUE TITLE
Evaluate method doesn't work without prior training

### ISSUE THREAD

**Issue by ajaysub110** [SforAiDl/genrl#91]
Say I do, 

```python
env = gym.make(...)
algo = Algorithm('mlp',env)
algo.evaluate(algo) # without calling learn first
```
It gives errors in most algos since there are a few hyperparameters like epsilon in DQN that are defined only when `learn` is called. VPG too has some of these. Others, I haven't checked.

**Comment by Zeus3101** [comment]
For this, we do expect to run evaluate only after Trainer has run at least once right?

**Comment by ajaysub110** [comment]
Not necessarily I think. We could have a pretrained model that we would just like to evaluate without training. That doesn't work with our current code

**Comment by Zeus3101** [comment]
I checked it with all the algos. It can only be used from the trainer so it's working fine.
